name: PR title must include JIRA key
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          if echo "$TITLE" | grep -Eq '^[A-Z]+-[0-9]+:'; then
            echo "OK: $TITLE"
          else
            echo "ERROR: el título debe empezar con 'PROY-123: '"
            exit 1
          fi
